import type { Product } from "./types"

export const featuredProducts: Product[] = [
  {
    id: "dome-camera-1",
    name: "HD Dome Security Camera",
    description: "High-definition dome security camera with night vision and wide-angle lens.",
    price: 3999,
    discount: 10,
    discountedPrice: 3599,
    category: "Dome Cameras",
    image: "https://m.media-amazon.com/images/I/61erifgUv7L.jpg",
    features: [
      "1080p HD resolution",
      "Night vision up to 30m",
      "120° wide-angle lens",
      "IP66 weatherproof rating",
      "Motion detection alerts",
    ],
    specifications: {
      Resolution: "1080p HD",
      "Night Vision": "30m",
      "Field of View": "120°",
      Weatherproof: "IP66",
      Power: "DC 12V",
      Storage: "MicroSD up to 128GB",
    },
    isNew: true,
    inStock: true,
    rating: 4.5,
    reviews: 28,
  },
  {
    id: "bullet-camera-1",
    name: "4K Bullet Security Camera",
    description: "Ultra HD bullet security camera with long-range night vision and AI detection.",
    price: 5999,
    category: "Bullet Cameras",
    image:
      "https://computerbaba.co.in/wp-content/uploads/2023/02/HIKVISION-DS-2CE16U1T-ITPF-4K-Bullet-Camera-at-best-price.jpg.webp",
    features: [
      "4K Ultra HD resolution",
      "Night vision up to 50m",
      "AI human detection",
      "IP67 weatherproof rating",
      "Two-way audio",
    ],
    specifications: {
      Resolution: "4K Ultra HD",
      "Night Vision": "50m",
      "Field of View": "110°",
      Weatherproof: "IP67",
      Power: "DC 12V",
      Storage: "MicroSD up to 256GB",
    },
    isNew: false,
    inStock: true,
    rating: 4.8,
    reviews: 42,
  },
  {
    id: "nvr-system-1",
    name: "8-Channel NVR System",
    description: "Complete 8-channel NVR system with 2TB storage and remote viewing capabilities.",
    price: 12999,
    discount: 15,
    discountedPrice: 11049,
    category: "NVR Systems",
    image:
      "https://5.imimg.com/data5/SELLER/Default/2021/9/RJ/UC/JY/7808107/hikvision-poe-8-ch-nvr-ds-7608ni-8p-1-500x500.jpg",
    features: [
      "8-channel recording",
      "2TB surveillance hard drive",
      "H.265+ video compression",
      "Remote viewing via app",
      "Motion detection recording",
    ],
    specifications: {
      Channels: "8",
      Storage: "2TB HDD (expandable to 8TB)",
      "Video Format": "H.265+",
      Resolution: "Up to 4K",
      Connectivity: "HDMI, VGA, Ethernet",
      "Remote Access": "Mobile app & web interface",
    },
    isNew: false,
    inStock: true,
    rating: 4.7,
    reviews: 36,
  },
  {
    id: "ip-camera-1",
    name: "Wireless IP Camera",
    description: "Smart wireless IP camera with pan-tilt-zoom functionality and AI detection.",
    price: 4999,
    category: "IP Cameras",
    image: "https://5.imimg.com/data5/SELLER/Default/2022/12/QQ/HR/EG/1730795/hikvision-wireless-ip-camera.PNG",
    features: [
      "1080p HD resolution",
      "Pan-tilt-zoom control",
      "Two-way audio",
      "AI person detection",
      "Cloud storage option",
    ],
    specifications: {
      Resolution: "1080p HD",
      "Pan/Tilt": "355° pan, 90° tilt",
      Connectivity: "Wi-Fi, Ethernet",
      Audio: "Built-in mic and speaker",
      Storage: "Cloud or MicroSD up to 128GB",
      Power: "DC 5V",
    },
    isNew: true,
    inStock: true,
    rating: 4.6,
    reviews: 52,
  },
]

export const allProducts: Product[] = [
  ...featuredProducts,
  {
    id: "dome-camera-2",
    name: "Mini Dome Camera",
    description: "Compact dome camera ideal for indoor surveillance with clear night vision.",
    price: 2499,
    discount: 8,
    discountedPrice: 2299,
    category: "Dome Cameras",
    image:
      "https://us-legacy.hikvision.com/sites/default/files/styles/zoom600/public/ds-2cd25x3g0-iws-_1.png?itok=HZmzCDw4",
    features: [
      "720p HD resolution",
      "Night vision up to 15m",
      "90° viewing angle",
      "Easy installation",
      "Motion detection",
    ],
    specifications: {
      Resolution: "720p HD",
      "Night Vision": "15m",
      "Field of View": "90°",
      "Indoor/Outdoor": "Indoor",
      Power: "DC 12V",
      Storage: "DVR/NVR required",
    },
    isNew: false,
    inStock: true,
    rating: 4.2,
    reviews: 18,
  },
  {
    id: "dvr-system-1",
    name: "4-Channel DVR System",
    description: "Complete 4-channel DVR system with 1TB storage and 4 HD cameras included.",
    price: 8999,
    category: "DVR Systems",
    image: "https://srgroup.net.in/wp-content/uploads/2021/11/4ch-hc.jpg",
    features: [
      "4-channel recording",
      "1TB surveillance hard drive",
      "4 HD cameras included",
      "Mobile viewing app",
      "Motion detection alerts",
    ],
    specifications: {
      Channels: "4",
      Storage: "1TB HDD",
      "Cameras Included": "4 x 1080p HD",
      "Video Format": "H.264",
      Connectivity: "HDMI, VGA",
      "Remote Access": "Mobile app",
    },
    isNew: false,
    inStock: true,
    rating: 4.4,
    reviews: 24,
  },

  {
    id: "dvr-system-2",
    name: "8-Channel DVR System",
    description: "Complete 8-channel DVR system with 1TB storage and 4 HD cameras included.",
    price: 8999,
    discount: 12,
    discountedPrice: 7919,
    category: "DVR Systems",
    image: "https://cpimg.tistatic.com/09227371/b/4/DS-6008HGHI-F1-Hikvision-8-Channel-DVR.jpg",
    features: [
      "4-channel recording",
      "1TB surveillance hard drive",
      "4 HD cameras included",
      "Mobile viewing app",
      "Motion detection alerts",
    ],
    specifications: {
      Channels: "4",
      Storage: "1TB HDD",
      "Cameras Included": "4 x 1080p HD",
      "Video Format": "H.264",
      Connectivity: "HDMI, VGA",
      "Remote Access": "Mobile app",
    },
    isNew: false,
    inStock: true,
    rating: 4.4,
    reviews: 24,
  },
]
